<!--
kate: indent-width 4; word-wrap-column 74; default-dictionary en_AU
Copyright (C) 2020, Marek Gagolewski, https://www.gagolewski.com
This material is licensed under the Creative Commons BY-NC-ND 4.0 License.
-->

# Setting Up the R Environment  {#appendix:rintro}



{ LATEX \color{gray} }

**TODO** In this chapter, we will:

* ...

* ...


{ LATEX \normalcolor }




<!--

TODO: Mention knitr+markdown and add OnTrack exercises?
This can be left for the Deep R book.

-->



## Installing R

R and Python are *the* languages of modern data science.
The former is slightly more oriented towards data modelling,
analysis and visualisation as well as statistical computing.
It has a gentle learning curve, which makes is very suitable even
for beginners -- just like us!

R is available for Windows as well as MacOS, Linux and other Unix-like
operating systems.
It can be downloaded from the R project website,
see https://www.r-project.org/ (or installed through system-specific package
repositories).


Remark.

: From now on we assume that you have installed the newest version of the
R environment.



## Installing an IDE

As we wish to make our first steps with the R language
as stress- and hassle-free as possible, let's stick to a very user-friendly
development environment called RStudio, which can be downloaded from
https://rstudio.com/products/rstudio/ (choose RStudio Desktop Open Source Edition).


Remark.

: There are of course many other options for working with R, both interactive
and non-interactive, including Jupyter Notebooks (see https://irkernel.github.io/),
dynamically generated reports (see https://yihui.org/knitr/options/)
and plain shell scripts executed from a terminal.
However, for now let's leave that to more
advanced users.


## Installing Recommended Packages

Once we get the above up and running, from within RStudio,
we need to install a few packages which we're going to use during the course
of this course. Execute the following commands in the R console
(bottom-left RStudio pane):

```{r recommended_packages,results='asis',echo=FALSE}
library("knitr")
library("bookdown")
library("stringi")
fs <- list.files(".", "\\.Rmd$", full=TRUE)
pkgs <- unlist(lapply(fs, function(f)
    na.omit(stri_match_first_regex(
        readLines(f), "^library\\(['\"]?(.*?)['\"]?\\)")[,2])))
pkgs <- setdiff(pkgs, c("bookdown", "knitr"))
pkgs <- c(pkgs, "tensorflow", "keras")
pkgs <- stri_unique(stri_sort(pkgs))
outpkgs <- stri_paste('"', pkgs, '"', sep="")
outpkgs <- stri_flatten(stri_wrap(stri_flatten(outpkgs, collapse=", "), 55), collapse="\n    ")
cat('```r\n')
cat(sprintf('pkgs <- c(%s)\n', outpkgs))
cat('install.packages(pkgs)\n')
cat('```\n\n')
```


What is more, in order to be able to play with neural networks,
we will need some Python environment, for example
the Anaconda Distribution Python 3.x, see
https://www.anaconda.com/distribution/.


Remark.

: Do **not** download Python 2.7.

Installation instructions can be found at
https://docs.anaconda.com/anaconda/install/.
This is required for the R packages tensorflow and keras,
see https://tensorflow.rstudio.com/installation/.
Once this is installed, execute the following R commands in the console:

```r
library("tensorflow")
install_tensorflow()
```


## First R Script in RStudio

Let's open RStudio and perform the following steps:

1.  Create a New Project where we will store all the scripts
    related to this book. Click *File* → *New Project*
    and then choose to start in a brand new working directory,
    in any location you like.
    Choose *New Project* as the project type.


    From now on, we are assuming that the project name is *LMLCR*
    and the project has been opened. All source files we create
    will be relative to the project directory.

2.  Create a new R source file, *File* → *New File* → *R Script*.
    Save the file as, for example, *sandbox_01.R*.

    The source editor (top left pane) behaves just like any other text editor.
    Standard keyboard shortcuts are available, such as CTRL+C
    and CTRL+V (Cmd+C and Cmd+V on MacOS) for copy and paste, respectively.

    A list of keyboard shortcuts is available at
    https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts

3.  Input the following R code into the editor:

    ```r
    # My first R script
    # This is a comment

    # Another comment

    # Everything from '#' to the end of the line
    #     is ignored by the R interpreter
    print("Hello world") # prints a given character string
    print(2+2) # evaluates the expression and prints the result
    x <- seq(0, 10, length.out=100) # a new numeric vector
    y <- x^2 # squares every element in x
    plot(x, y, las=1, type="l") # plots y as a function of x
    ```

4.  Execute the 5 above commands, line by line,
    by positioning the keyboard cursor accordingly and
    pressing Ctrl+Enter (Cmd+Return on MacOS).

    Each time, the command will be copied to the console
    (bottom-left pane)
    and evaluated.

    The last line generates a nice plot which will appear in the
    bottom-right pane.

While you learn, we recommend that you get used to writing your
code in an R script and executing it just as we did above.

On a side note, you can execute (source) the whole script
by pressing Ctrl+Shift+S (Cmd+Shift+S on MacOS).




## Exercises

### First Steps with Vectors

{ BEGIN exercise }
Print the contents of the `x` and `y` vectors that we have
created above
by issuing the `print(x)` and `print(y)` commands.
Here, by a *vector* we mean a sequence of numbers.
{ END exercise }


{ BEGIN exercise }
Check the length of the vectors by applying `length(x)`
and `length(y)`. Read the results.
{ END exercise }

{ BEGIN exercise }
Inspect a few elements in both `x` and `y`,
for example `y[1]` gives the first element
and `y[length(x)]` -- the last one.
{ END exercise }


### Basic Plotting

{ BEGIN exercise }
Read the manual page on the `seq()` function
by executing the `?seq` command.
{ END exercise }


{ BEGIN exercise }
Using the `seq()` function with appropriate parameters,
create a vector `x2` with elements 0, 0.1, 0.2, ..., 1.0.
{ END exercise }

Remark.

:  In one of the above examples, `<-` denotes the assignment operator.
   By writing `x <- ...` we create a new named object (variable) called `x`.
   Use a similar notation to create `x2`.

{ BEGIN exercise }
Then create a vector `y2` that gives the square root of each element in `x2`.
Use the `sqrt()` function.
{ END exercise }


{ BEGIN exercise }
Plot `y2` as a function of `x2`.
{ END exercise }


Remark.

: You can access the list of graphical parameters that the `plot()`
    function takes by executing `?plot.default` and `?plot`.
    For example, `plot(..., col="red")` draws a red curve.
    See `colours()` for the list of available colours.
    Check out the meaning of the `lty` and `lwd` parameters.
    Moreover, change `type="l"` to `type="p"`.
    Check out the meaning of the `pch` and `cex` parameters.





{ LATEX \color{gray} }

. . .

**TODO** .....


. . .

{ LATEX \normalcolor }


Next chapter...

